#!/bin/bash

PWD="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

if [ ! -f $PWD/.env ]; then
    cp $PWD/.env.example $PWD/.env
fi

source $PWD/.env

NAME=$POD_NAME
EXEC="sh"

## check docker running.
docker_state=$(docker info >/dev/null 2>&1)
while [ $? -ne 0 ]
do
    echo "Docker does not seem to be running, sleep 2.."
    sleep 2
done

## some init scripts.

[ "$1" = "init" ] && {
    echo 'init.'
}

[ "$1" = "" ] && {
    docker build --rm -t $NAME .
}

[ "$1" = "test" ] && {
    docker run --rm -ti $NAME --log.level=debug \
    --experimental.localPlugins.traefik-auth.modulename=github.com/zzci/traefik-auth \
    --experimental.localPlugins.fail2ban.modulename=github.com/tomMoulard/fail2ban \
    --experimental.localPlugins.traefik-real-ip.modulename=github.com/soulbalz/traefik-real-ip
}

[ "$1" = "rm" ] && {
    docker-compose down
}

[ "$1" = "e" ] && {
    if [ "$2" != "" ]; then
        EXEC=$2
    fi
    docker exec -ti $NAME $EXEC
}

[ "$1" = "run" ] && {
    docker-compose down
    docker-compose up -d
}

exit 0
